file_format: "1"
id: sofle-5-way
name: Sofle-5-way
type: shield
url: https://github.com/josefadamcik/SofleKeyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - sofle-e_left
  - sofle-e_right