file_format: "1"
id: sofle-x
name: Sofle-x
type: shield
url: https://github.com/josefadamcik/SofleKeyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - sofle-x_left
  - sofle-x_right